config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :crowd_funds
    resources :funders
    resources :causes
    resources :legal_entities
    resources :cause_admins
    resources :monthly_trigger_charges
    resources :crowd_fund_memberships, except: [:new, :create]

    root to: "crowd_funds#index"
  end

  devise_for :cause_admins, only: [:sessions, :passwords], path: ''

  root 'crowd_funds#index'

  post '/funders' => 'funders#create'

  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'
  get '/sign_up' => 'pages#sign_up'

  resources :crowd_funds, path: 'campaigns', only: [:show, :index] do
    get :dashboard, on: :member
    get :v2, on: :member
    get :super_dashboard, on: :collection
  end

  resources :causes, only: [] do
    get :acceptance, on: :member
    post :update_terms_of_service_acceptance, on: :member
  end
end

app/models/crowd_fund.rb
class CrowdFund < ApplicationRecord
  require 'SendGridEmails'
  include FriendlyId
  friendly_id :name, :use => [:slugged]
  has_many :crowd_fund_memberships
  belongs_to :cause
  validates :cause, presence: true

  def name_except_for_fight_for_15
    return 'Will Guzzardi' if name === 'Fight for $15'

    return name
  end

  def disclaimer_paragraphs_for_form
    disclaimer_paragraphs.join(" // ")
  end

  def charge_funders(number_of_triggers,
                     api_to_charge = Stripe::Charge,
                     log=STDOUT)

    log.write("Preparing to charge #{crowd_fund_memberships.size} funders...")
    log.write("\n")

    success_count = 0
    error_count = 0
    inactive = crowd_fund_memberships.where.not(status: 'active')
    inactive_count = inactive.size
    active_memberships = crowd_fund_memberships.select{|cfm| cfm.status == "active"}

    active_memberships.each do |membership|
      # begin
        log.write("💸 Charging someone...")
        log.write("\n\n")

        if flat_monthly_amount
          membership.charge_member_for_month(api_to_charge)
        else
          membership.charge_member_based_on_triggers(number_of_triggers, api_to_charge)
        end

        success_count += 1
        log.write("✅ Succeeded!")

        # MonthlyChargesMailer.monthly_charge(membership).deliver_now
        SendGridEmails.monthly_charge(membership, number_of_triggers)

        log.write("\n\n")
      # rescue => error
      #   error_count += 1
      #   log.write("🚨 Error charging card! #{error}")
      #   log.write("\n\n")
      #   false
      # end
    end

    log.write("🙌 🙌 🙌 Successfully charged #{success_count} funders.")
    log.write("\n\n")
    log.write("🚨 🚨 🚨 Failed to charge #{error_count} funders.")
    log.write("\n\n")
    log.write("💀 💀 💀 Did not charge #{inactive_count} inactive funders.")
    log.write("\n\n")

    return crowd_fund_memberships
  end

  def url
    "https://wegivewhen.com/campaigns/#{slug}"
  end

end

app/controllers/admin/crowd_funds_controller.rb
module Admin
  class CrowdFundsController < Admin::ApplicationController

    def valid_action?(name, resource = resource_class)
      %w[destroy].exclude?(name.to_s) && super
    end

    def find_resource(param)
      CrowdFund.find_by!(slug: param)
    end

    def resource_params
      params["crowd_fund"]["disclaimer_paragraphs"] = params["crowd_fund"]["disclaimer_paragraphs_for_form"].split(" // ") || []

      params.require("crowd_fund").permit(*dashboard.permitted_attributes, disclaimer_paragraphs: [])
    end

  end
end

app/controllers/crowd_funds_controller.rb
require 'csv'

class CrowdFundsController < ApplicationController

  before_action :authenticate_cause_admin!, only: [:dashboard, :super_dashboard]
  before_action :check_crowd_fund_cause!, only: [:dashboard]
  before_action :check_super_admin!, only: [:super_dashboard]

  def index
    @crowd_funds_by_popularity = CrowdFund.all.sort_by do |crowd_fund|
      crowd_fund.crowd_fund_memberships.count
    end.reverse
  end

  def show
    @crowd_fund = CrowdFund.friendly.find(params[:id])

    if @crowd_fund.id == 2
      @funder_required_details = [
        'firstName', 'lastName', 'occupation', 'employer', 'email',
        'address', 'city', 'usState', 'zip',
      ]
    else
      @funder_required_details = [
        'firstName', 'lastName', 'email', 'city', 'usState', 'zip',
      ]
    end
  end

  def v2
    @crowd_fund = CrowdFund.friendly.find(params[:id])

    if @crowd_fund.id == 2
      @funder_required_details = [
        'firstName', 'lastName', 'occupation', 'employer', 'email',
        'address', 'city', 'usState', 'zip',
      ]
    else
      @funder_required_details = [
        'firstName', 'lastName', 'email', 'city', 'usState', 'zip',
      ]
    end
  end

  def dashboard
    @crowd_fund = CrowdFund.includes(crowd_fund_memberships: [:funder])
                           .friendly.find(params[:id])

    @cause = @crowd_fund.cause

    @membership_headers = CrowdFundMembership.dashboard_row_headers

    @membership_rows = @crowd_fund.crowd_fund_memberships.order(created_at: :desc).map do |membership|
      membership.to_dashboard_row
    end

    respond_to do |format|
      format.html
      format.csv {
        send_data to_csv(@membership_headers, @membership_rows), filename: csv_filename
      }
    end
  end

  def super_dashboard
    @crowd_fund_memberships = CrowdFundMembership.all

    @membership_headers = CrowdFundMembership.super_dashboard_row_headers

    @membership_rows = @crowd_fund_memberships.order(:crowd_fund_id, created_at: :desc).map do |membership|
      membership.to_super_dashboard_row
    end

    respond_to do |format|
      format.html
      format.csv {
        send_data to_csv(@membership_headers, @membership_rows), filename: csv_filename
      }
    end
  end

  private

  def check_crowd_fund_cause!
    return true if current_cause_admin.super_admin == true

    crowd_fund = CrowdFund.friendly.find(params[:id])
    correct_cause = current_cause_admin.cause

    if crowd_fund.cause != correct_cause
      redirect_to root_url, alert: 'That\'s not your crowd fund, don\'t play.'
    end
  end

  def check_super_admin!
    return true if current_cause_admin.super_admin == true

    redirect_to root_url, alert: 'That\'s not your crowd fund, don\'t play.'
  end

  def to_csv(headers, rows)
    CSV.generate { |csv|
      csv << headers
      rows.each { |row| csv << row }
    }
  end

  def csv_filename
    "#{@crowd_fund.name} - "\
    "GiveWhen - "\
    "#{DateTime.current.strftime("%-m/%e/%y %r")}.csv"
  end

end

app/views/crowd_funds/dashboard.html.erb
<div class="campaigner-navbar">
  <span class="p-text"><%= @crowd_fund.name %> Data</span>
  <%= link_to "See Your Crowd Funding Page", crowd_fund_url(@crowd_fund) %>
  <%= link_to "Download CSV", dashboard_crowd_fund_url(@crowd_fund, format: :csv) %>
  <%= if @cause.tos_unsigned? then link_to "Accept TOS", acceptance_cause_url(@cause) else 'TOS Signed' end %>
  <%= link_to('Log Out', destroy_cause_admin_session_path, method: :delete, style: "float: right") %>
</div>

<div class="summary-stats">
  <!-- <div><span class="summary-stat">Total raised</span>: TK</div> -->
  <div><span class="summary-stat">Backers</span>: <%= @membership_rows.count %></div>
  <!-- <div><span class="summary-stat">Pledged per event</span>: TK</div> -->
  <!-- <div><span class="summary-stat">Pledged monthly max</span>: TK</div> -->
</div>

<table class="dashboard">
  <thead>
    <tr>
      <% @membership_headers.each do |header| %>
        <th><%= header %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @membership_rows.each_with_index do |membership_row, index| %>
      <tr class=<%= index.odd? ? 'odd' : 'even' %>>
        <% membership_row.each do |row| %>
          <td><%= row %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/crowd_funds/index.html.erb
<div class="page__wrapper">

  <div class="navbar">
    <div class="hero__area">
      <img src='/heart.svg' id="heart" />
      <span class="text">Give<span style="font-weight: bold;">When</span></span>
    </div>

    <div class="navlinks">
      <%= link_to 'Learn How It Works',
                  '/sign_up' %>
      <%= link_to 'Sign In',
                  '/sign_in' %>
    </div>
  </div>

  <div class="tagline">
    <div>The world's first trigger-based fundraising platform.</div>
    <br/>
    <div class="tagline__strong">So you can take on powerful forces and build a better world.</div>
  </div>

  <div class="our__campaigns">
    <div class="our__campaigns__text">
      <h2>Our Campaigns</h2>
      <p style="font-weight: lighter;">
        Whether it's every time an opponent gets corporate cash, or every time a homelessness organization places someone into a job, our clients are turning real-world events into sustained support for their cause.
      </p>
      <p style="margin: 50px 0;">Check out trigger-based fundraising in action:</p>
      <% @crowd_funds_by_popularity.each do |crowd_fund| %>
        <div style="margin: 20px 0;">
          <%= link_to crowd_fund.name_except_for_fight_for_15, crowd_fund_url(crowd_fund), style: "text-decoration: none;" %>
        </div>
      <% end %>
    </div>
    <div class="capitol__background__image">
    </div>
  </div>

  <div class="get__in__touch">
    <h2 style="font-size: 50px; font-weight: lighter; margin: 10px 0; text-align: center;">Get in touch</h2>

    <div class="typeform-widget" data-url="https://benj11.typeform.com/to/rSxL1K" data-transparency="100" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 400px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;" > powered by <a href="https://www.typeform.com/examples/forms/contact-form-template/?utm_campaign=rSxL1K&amp;utm_source=typeform.com-8630826-Basic&amp;utm_medium=typeform&amp;utm_content=typeform-embedded-contactform&amp;utm_term=EN" style="color: #999" target="_blank">Typeform</a> </div>
  </div>

  <div style="padding: 20px; text-align: center; background-color: #f1f6f9;
        color: #686d6e;">
    <p style="font-size: 1.2em; margin: 30px">created by <a href="/"
      style="text-decoration: none">Give<span style="font-weight: bold;">When</span></a>
    </p>
    <p>
      <a href='/terms' style="font-size: 0.9em; text-decoration: none">
        Terms of Service
      </a>
      &nbsp;
      &nbsp;
      &nbsp;
      <a href='/privacy' style="font-size: 0.9em; text-decoration: none">
        Privacy Policy
      </a>
    </p>
  </div>

</div>

app/views/crowd_funds/show.html.erb
<%= react_component(
  "NewCrowdFundPage",
  props: {
    crowdFundId: @crowd_fund.id,
    stripePublishableKey: ENV['STRIPE_PUBLISHABLE_KEY'],
    airbrakeProjectId: ENV['AIRBRAKE_PROJECT_ID'],
    airbrakeProjectKey: ENV['AIRBRAKE_PROJECT_KEY'],
    funderRequiredDetails: @funder_required_details,

    # Defaults
    defaultSelectedAmountInCents: @crowd_fund.default_selected_amount_in_cents,
    monthlyMultiplier: @crowd_fund.monthly_max_multiplier,

    # Social
    twitterMessage: @crowd_fund.twitter_message,
    suggestedEmailSubject: @crowd_fund.suggested_email_subject,
    suggestedEmailBody: @crowd_fund.suggested_email_body,

    # Foe
    foeHeader: @crowd_fund.foe_header,
    foeSubhead: @crowd_fund.foe_subhead,
    foeImgUrl: @crowd_fund.foe_img_url,
    foeHex: @crowd_fund.foe_hex,

    # Friend
    friendHeader: @crowd_fund.friend_header,
    friendSubhead: @crowd_fund.friend_subhead,
    friendImgUrl: @crowd_fund.friend_img_url,
    friendHex: @crowd_fund.friend_hex,

    callToActionSentence: @crowd_fund.call_to_action_sentence,
    theoryOfChangeSentence: @crowd_fund.theory_of_change_sentence,
    smallLogoImgPath: @crowd_fund.logo_img_path,
    signUpButtonColor: @crowd_fund.sign_up_button_hex,
    flatMonthlyAmount: @crowd_fund.flat_monthly_amount,

    disclaimerParagraphs: @crowd_fund.disclaimer_paragraphs
  })
%>

app/views/crowd_funds/super_dashboard.html.erb
<div class="campaigner-navbar">
  <span class="p-text">Super Dashboard</span>
  <%= link_to('Log Out', destroy_cause_admin_session_path, method: :delete, style: "float: right") %>
</div>

<div class="summary-stats">
  <!-- <div><span class="summary-stat">Total raised</span>: TK</div> -->
  <div><span class="summary-stat">Backers</span>: <%= @membership_rows.count %></div>
  <!-- <div><span class="summary-stat">Pledged per event</span>: TK</div> -->
  <!-- <div><span class="summary-stat">Pledged monthly max</span>: TK</div> -->
</div>

<table class="dashboard">
  <thead>
    <tr>
      <% @membership_headers.each do |header| %>
        <th><%= header %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @membership_rows.each_with_index do |membership_row, index| %>
      <tr class=<%= index.odd? ? 'odd' : 'even' %>>
        <% membership_row.each do |row| %>
          <td><%= row %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/crowd_funds/v2.html.erb
<%= react_component(
  "NewCrowdFundPage",
  props: {
    crowdFundId: @crowd_fund.id,
    stripePublishableKey: ENV['STRIPE_PUBLISHABLE_KEY'],
    airbrakeProjectId: ENV['AIRBRAKE_PROJECT_ID'],
    airbrakeProjectKey: ENV['AIRBRAKE_PROJECT_KEY'],
    funderRequiredDetails: @funder_required_details,

    # Defaults
    defaultSelectedAmountInCents: @crowd_fund.default_selected_amount_in_cents,
    monthlyMultiplier: @crowd_fund.monthly_max_multiplier,

    # Social
    twitterMessage: @crowd_fund.twitter_message,
    suggestedEmailSubject: @crowd_fund.suggested_email_subject,
    suggestedEmailBody: @crowd_fund.suggested_email_body,

    # Foe
    foeHeader: @crowd_fund.foe_header,
    foeSubhead: @crowd_fund.foe_subhead,
    foeImgUrl: @crowd_fund.foe_img_url,
    foeHex: @crowd_fund.foe_hex,

    # Friend
    friendHeader: @crowd_fund.friend_header,
    friendSubhead: @crowd_fund.friend_subhead,
    friendImgUrl: @crowd_fund.friend_img_url,
    friendHex: @crowd_fund.friend_hex,

    callToActionSentence: @crowd_fund.call_to_action_sentence,
    theoryOfChangeSentence: @crowd_fund.theory_of_change_sentence,
    smallLogoImgPath: @crowd_fund.logo_img_path,
    signUpButtonColor: @crowd_fund.sign_up_button_hex,

    disclaimerParagraphs: @crowd_fund.disclaimer_paragraphs
  })
%>