config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :crowd_funds
    resources :funders
    resources :causes
    resources :legal_entities
    resources :cause_admins
    resources :monthly_trigger_charges
    resources :crowd_fund_memberships, except: [:new, :create]

    root to: "crowd_funds#index"
  end

  devise_for :cause_admins, only: [:sessions, :passwords], path: ''

  root 'crowd_funds#index'

  post '/funders' => 'funders#create'

  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'
  get '/sign_up' => 'pages#sign_up'

  resources :crowd_funds, path: 'campaigns', only: [:show, :index] do
    get :dashboard, on: :member
    get :v2, on: :member
    get :super_dashboard, on: :collection
  end

  resources :causes, only: [] do
    get :acceptance, on: :member
    post :update_terms_of_service_acceptance, on: :member
  end
end

app/controllers/admin/causes_controller.rb
module Admin
  class CausesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Cause.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Cause.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController

  before_action :authenticate_cause_admin!
  before_action :authenticate_correct_cause

  def acceptance
    @cause = Cause.find_by_id(params[:id])
  end

  def update_terms_of_service_acceptance
    @cause = Cause.find_by_id(params[:id])
    @stripe_account_id = @cause.stripe_account_id

    raise "No stripe cause ID in our database!" unless @stripe_account_id

    @cause = Cause.find_by_id(params[:id])
    @now = Time.now.to_i
    @ip = request.remote_ip # Assumes you're not using a proxy

    acct = Stripe::Account.retrieve(@stripe_account_id)
    acct.tos_acceptance.date = @now
    acct.tos_acceptance.ip = @ip

    if acct.save
      if @cause.update({ tos_acceptance_date_in_seconds: @now, tos_acceptance_ip: @ip })
        redirect_to dashboard_crowd_fund_url(@cause.crowd_funds.first)
      end
    end
  end

  private

  def authenticate_correct_cause
    correct_cause = current_cause_admin.cause

    if Cause.find_by_id(params[:id]) != correct_cause
      redirect_to root_url, alert: 'That\'s not your cause, don\'t play.'
    end
  end

end

app/views/causes/about.html.erb
<div class="page__wrapper">
  <div class="hero">
    <img src='/heart.svg' height="80" width="80" style="position: relative; top: 15px; left: 30px;" />
    Give<span style="font-weight: bold;">When</span>
  </div>

  <div class="tagline">
    <div>Trigger-based fundraising so you can</div>
    <div class="tagline__strong">take on powerful forces and change the world.</div>
  </div>

  <div class="what__its__about">

    <p>You used to have to ask your supporters to give once, or give some excuse for them to give monthly.</p>

    <p>Now, causes can ask supporters to sign up to automatically donate every time something happens in the real world. Like...</p>

    <p style="font-style: italic;">Automatically donate every time:</p>

    <table class="all__the__examples">
      <tr>
        <td>Your opponent tweets</td>
        <td>A disaster needs a response</td>
      </tr>
      <tr>
        <td>Trump tweets (100/mo)</td>
        <td>Jeff Sessions tweets</td>
      </tr>
      <tr>
        <td>Trump lies (9/mo, Politifact)</td>
        <td>You get press</td>
      </tr>
      <tr>
        <td>Your opponent takes a corporate check</td>
        <td>You help someone in need</td>
      </tr>
      <tr>
        <td>You get 100 petition signatures</td>
        <td>You get a politician to sign on</td>
      </tr>

    </table>

    <p>Or anything you choose.</p>

    <p>GiveWhen is a free platform that makes giving easy, sustainable, and meaningful.</p>

    <p>Raise more money, from more people, more often, by combining the best practices of crowdfunding and sustained monthly giving.</p>

    <p>For supporters, giving is easy and meaningful. We also make it affordable for causes: supporters cover your processing fees.</p>

    <p>Talk to us about getting started with Give When:</p>

    <div class="typeform-widget" data-url="https://benj11.typeform.com/to/rSxL1K" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 500px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;" > powered by <a href="https://www.typeform.com/examples/forms/contact-form-template/?utm_campaign=rSxL1K&amp;utm_source=typeform.com-8630826-Basic&amp;utm_medium=typeform&amp;utm_content=typeform-embedded-contactform&amp;utm_term=EN" style="color: #999" target="_blank">Typeform</a> </div>
  </div>
</div>

app/views/causes/acceptance.html.erb
<div class="causes__header">
  <div id="give-when-logo">
    <span>Give</span><span id="when">When</span>
  </div>
</div>
<div class="center__column">
  <div class="cause__name">
    <strong><%= @cause.name %></strong>
  </div>
  <br/>
  <div>
    <p>You agree to our <%= link_to 'Terms of Service', terms_url %> and the <a target="_blank" href="https://stripe.com/us/connect-account/legal">Stripe Connected Account Agreement</a>.</p>
  </div>
  <div>
    <p>You also agree that your acceptance of payments is provided subject to the Stripe Connected Account Agreement:</p>
    <p style="font-style: italic;">Payment processing services for causes on GiveWhen are provided by Stripe and are subject to the Stripe Connected Account Agreement, which includes the Stripe Terms of Service (collectively, the “Stripe Services Agreement”). By agreeing to this agreement or continuing to operate as a cause on GiveWhen, you agree to be bound by the Stripe Services Agreement, as the same may be modified by Stripe from time to time. As a condition of GiveWhen enabling payment processing services through Stripe, you agree to provide GiveWhen accurate and complete information about you and your business, and you authorize GiveWhen to share it and transaction information related to your use of the payment processing services provided by Stripe.</p>
  </div>
  <div id="i-agree-wrapper">
    <%= form_tag(update_terms_of_service_acceptance_cause_url(@cause), method: "POST") do %>
      <button id="i-agree">
        I agree
      </button>
    <% end %>
  </div>
</div>